name: Format
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.14 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14
    - name: Install dependencies
      id: install
      run: |
        make install

    - name: Format code
      id: format
      run: |
        make format 

    - name: Lint code
      id: lint
      run: 
        make lint 

    - name: Test code
      id: test
      run: 
        make test 
